### ISSUE TITLE
Random stuff

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/HiMAP#4]
[x]  Remove the tapir reference tree from the part01 data input?
[  ]  Write up at least the basic requirements for each step (i.e. for step03, it requires a main directory where each subdir contains the trimmed and FLASh-joined reads for an individual and each subdir is named with the ind name)--and make reference to the config file for this, since it where users would enter some of this info.
[  ]  Also, it'd be good to have the basics of how to run the various steps (even if it is just "python step01.py" or something simple like that). If you can pull together those basic kind of things, I can go through and start mocking up a more detailed readme/walkthrough that users would look at to learn how to use it.

**Comment by Woods26** [comment]
tapir reference tree removed
