### ISSUE TITLE
Transvestigator part of config.toml

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/HiMAP#5]
This section of the config.toml:
# list of species who's part01 came from transvestigator (needs to be parsed slightly different)
transvestigated_species_list = ['Bcor', 'Blat', 'Bzon', 'Afra', 'Bmin', 'Bjar', 'Aobl']

could be a bit confusing for folks. I think the issue is with the formatting of the gff files, right? Maybe we could make our script just deal with normal gff format (NCBI formatted things), and write a separate script to re-format gffs generated with Transvestigator? That way we can say "this script accepts normal gff format (NCBI format), and we've provided a script for re-formatting gffs generated with [link to transvestigator]".

It'd be good to have a little description of what is different in the formatting (so we can provide a general example of the type of formatting required).

**Comment by Woods26** [comment]
looks like this fix is working now
